import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import FormControl from "../components/Form";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>FOMO Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FormContainer>
        <FormControl />
      </FormContainer>
    </Container>
  );
};

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const FormContainer = styled.section`
  margin: 48px;
  width: 80%;
  background: #1f1e24;
  border-radius: 6px;
`;

export default Home;
